---
- name: Download Composer installer
  get_url:
    url: "https://getcomposer.org/installer"
    dest: "/tmp/installer.php"

- name: Run Composer installer
  command: "php /tmp/installer.php --install-dir=/usr/local/bin --filename=composer"
  become: true

- name: Remove Composer installer
  file:
    path: "/tmp/installer.php"
    state: absent