---
- name: Ensure MySQL service is running and enabled
  systemd:
    name: mysql
    state: started
    enabled: yes
    
- name: MySQL | restart mysql
  service:
    name: mysql
    state: restarted
  become: true